In [4]:
import numpy as np

In [5]:
np.array([20,30,40])

array([20, 30, 40])

In [9]:
matrixArr = [[1,2,3],[4,5,6]]
matrixArr

[[1, 2, 3], [4, 5, 6]]

In [10]:
np.array(matrixArr)

array([[1, 2, 3],
       [4, 5, 6]])

### arange

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros, ones

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### linspace

In [20]:
## verilen aralığı kaça bölüceğini söylersin, otomatik böler

In [23]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [24]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

### eye (diagonal elemanları 1 olan matris)

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random (numpy da standart normal dağılımdan alır değerleri)

In [31]:
np.random.randn(3)  # dizi döndürür

array([ 1.13206304,  0.18239608, -0.51479385])

In [32]:
np.random.randn(3,4)

array([[ 0.19804745, -1.60926334,  0.25846517, -0.10650861],
       [ 1.05425133,  0.16426214,  0.96931507,  0.57603303],
       [-0.40643004,  0.53974628,  1.17401787, -0.81449217]])

In [37]:
np.random.randint(1,10) #1den 10 a kadar random int 

5

In [40]:
np.random.randint(1,10,4)

array([7, 4, 5, 1])

In [55]:
myNumpyArray = np.random.randint(0,100,20)

In [56]:
myNumpyArray

array([76, 37, 45, 30, 34, 68, 85, 66, 62,  7, 62, 44, 74, 95, 90, 57, 87,
       43, 90,  0])

### numpy array methods

In [58]:
myNumpyArray.reshape(4,5)

array([[76, 37, 45, 30, 34],
       [68, 85, 66, 62,  7],
       [62, 44, 74, 95, 90],
       [57, 87, 43, 90,  0]])

In [70]:
myNumpyArray

array([76, 37, 45, 30, 34, 68, 85, 66, 62,  7, 62, 44, 74, 95, 90, 57, 87,
       43, 90,  0])

In [63]:
myNumpyArray.min()

0

In [64]:
myNumpyArray.argmax() # index of max

13

In [67]:
myNumpyArray.argmin() # index of min

19

In [71]:
myNumpyArray.shape  # shape not a function, it is a attiribute

(20,)

## Numpy indexes

In [72]:
myArr = np.arange(0,15)

In [73]:
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
myArr[5]

5

In [75]:
myArr[3:5] # slicing

array([3, 4])

In [80]:
myArr[3:5] = -8

In [81]:
myArr

array([ 0,  1,  2, -8, -8,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
myArr2 = np.arange(0,24)

In [84]:
temp = myArr2[4:9]

In [85]:
temp

array([4, 5, 6, 7, 8])

In [86]:
temp[:] = 700

In [87]:
temp

array([700, 700, 700, 700, 700])

In [88]:
temp =100

In [89]:
temp

100

### copy()  -> bir dizinin kopyasını almak için, bunu almazsak yeni dizideki işlemlele orjinal diziyide değiştiririz!!

### matrix indexes

In [150]:
myList = [[10,20,30],[40,50,60],[70,80,90]]
matrix1 = np.array(myList)
matrix1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [151]:
matrix1[1,2]  # or matrix1[1][2]

60

In [152]:
# we can do slicing with matrix
matrix1[1:,:2]

array([[40, 50],
       [70, 80]])

In [156]:
matrix1[[0,2]]   #fancy indexing  

array([[10, 20, 30],
       [70, 80, 90]])

# operations  (with same index)

In [160]:
arr = np.random.randint(1,100,20)

In [161]:
arr

array([70, 31, 10, 53, 30, 74, 78, 19,  3, 65, 49, 49, 83, 28, 41, 12, 34,
        8, 78, 71])

In [170]:
arr[arr>24]

array([70, 31, 53, 30, 74, 78, 65, 49, 49, 83, 28, 41, 34, 78, 71])

In [177]:
arr[arr<24]

array([10, 19,  3, 12,  8])

In [182]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
arr3 = np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
arr2+arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [184]:
arr2-arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [185]:
arr2*arr3

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [187]:
arr2/arr3   # sıfıra bölüm olduğu için oraya nan yazdı

<ipython-input-187-0dda63729780>:1: RuntimeWarning: invalid value encountered in true_divide
  arr2/arr3   # sıfıra bölüm olduğu için oraya nan yazdı


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [189]:
np.sqrt(arr2*arr3) 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [192]:
np.max(arr2)

9

In [193]:
np.average(arr2)

4.5